-- Add lat/lng coordinates to events and scraped_events tables
ALTER TABLE events ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION;
ALTER TABLE events ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION;

ALTER TABLE scraped_events ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION;
ALTER TABLE scraped_events ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION;
