ALTER TABLE places ADD COLUMN IF NOT EXISTS main_category TEXT;
ALTER TABLE places ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE places ADD COLUMN IF NOT EXISTS subcategory TEXT;
ALTER TABLE places ADD COLUMN IF NOT EXISTS image_cover TEXT;
ALTER TABLE places ADD COLUMN IF NOT EXISTS image_thumb TEXT;
ALTER TABLE places ADD COLUMN IF NOT EXISTS image_set TEXT;
